package com.onlineservice.center.model;

public enum ServiceType {
	AC, WASHING_MACHINE, MIXER, REFRIGERATOR, AIR_COOLER, GEYSER, FAN, GAS_OVEN, MICROWAVE_OVEN, INDUCTION_OVEN, LAPTOP,
	DESKTOP, ELECTRICITY_FAULT, LPG_STOVE, WATER_PURIFIER, TV, CARPENTER, PLUMBER, CCTV, DTH, CHIMNEY
}
